### ISSUE TITLE
Add `shouldRender` to internal component-spec records

### ISSUE THREAD

**Issue by garyb** [purescript-halogen/purescript-halogen#513]
This would make it possible to predicate rendering on some kind of state equality function, but I don't want to expose it as part of the normal spec as it's a major footgun, but if someone _really_ needs it they could write their own `Component` constructor and make use of it.

**Comment by natefaubion** [comment]
Another option is to add something like https://github.com/natefaubion/purescript-spork/blob/master/src/Spork/Html/Core.purs#L181-L187 to `HTML`. It still relies on referential equality at some level though, but it might have less caveats with Halogen since a component instance isn't recreated once the lifecycle is mounted and it could still be encapsulated within a component scope.

**Comment by natefaubion** [comment]
ie, you could still do something like

```purescript
ui = H.component
  { render: H.memoized myEq render
  , eval
  }
  where
  render state = ...
  eval = ...
```

And it should "just work".

**Comment by garyb** [comment]
> positive equality on the state so that you could provide something like `Record.equal` if you needed to

Well... there's this operator called `not` that I discovered recently 😆

I don't really mind the formulation of it, was just something that seemed trivial to add and some people were talking about how to solve the "problem" of unnecessary renders in Slack today. The `HTML` thing seems like more of an investment of effort so unless it gives us something else much wanted I'd just be inclined to sling the `s -> s -> Boolean` in there.

**Comment by natefaubion** [comment]
The thunk primitives would give you better results in those benchmarks everyone talks about ;)

**Comment by garyb** [comment]
Closing this now we have thunks providing `memoized`, `lazy`, and such.
