### ISSUE TITLE
Bring guide to completion

### ISSUE THREAD

**Issue by linearray** [purescript-halogen/purescript-halogen#528]
I'd really like to see the halogen guide completed, because it's by far the easiest way to learn about halogen.

I can put in some time next week to write about lifecycle methods, provided that somebody who really knows what's going on plays editor. I cannot be much help with event sources, but I think this chapter is badly needed as well.

Anyone willing to team up and commit to this?

**Comment by garyb** [comment]
Sorry, I meant to reply to this days ago!

Once we get the next release out I'll definitely try and fill in the gaps - there's going to be a few changes (including event sources and subscriptions specifically, to hopefully make them more pleasant to use), so it's probably worth holding off till then.

**Comment by JordanMartinez** [comment]
I read through the guide (which seems to exclude the recent additions of `initializer` and `finalizer`) and came up with this flowchart:

![halogen](https://user-images.githubusercontent.com/8413037/41687940-b7ee0700-749e-11e8-8939-2cebbc149c6e.png)

**Comment by garyb** [comment]
Nice work! `initializer` and `finalizer` have been present for some time, but only recently become required (there was `component` vs `lifecycleComponent`). It's one of the places the current guide falls short.

**Comment by JordanMartinez** [comment]
Thanks! Ah, ok. Since you mentioned in above, what's the ETA for the next release?

I also realized that the above flowchart does not include a dotted line from the `initial state rendering` and `re-render state` nodes to the `Parent passes in value of INPUT type (i) to child)` node. Hmm... actually, the flowchart doesn't also clarify what happens when the Parent passes in the same input value (child gets potentially re-rendered) as opposed to a different one (e.g. child is destroyed and a new one is created)

I'm not sure whether you'd want to use the updated flowchart or not in your documentation. If so, I can submit a PR that adds that to the docs part of this project and license it using CC0 so neither of us have to worry about license problems now or in the future.

**Comment by JordanMartinez** [comment]
More complicated version, but better distinguishes how the whole thing works:
![halogen - grouped](https://user-images.githubusercontent.com/8413037/41812734-03ea51a0-76dd-11e8-8215-4ae448aa9558.png)

Note that this flowchart does not include what happens when a query evaluation done by a parent causes it to re-render its state, which passes in a new input value that destroys the old child and creates a new one. It still doesn't include the `initializer` and `finalizer` stuff as well, though I think I should add that after looking through the corresponding examples more

**Comment by safareli** [comment]
AFAICT there is no distinction between Root and non root components in halogen, you can call `runUI` any component even one which take something else other then `Unit` as input. for example you can pass some config as input to your root component instead of just Unit.

**Comment by JordanMartinez** [comment]
> AFAICT there is no distinction between Root and non root components in halogen, you can call runUI any component even one which take something else other then Unit as input. for example you can pass some config as input to your root component instead of just Unit.

The examples often passed in `Unit` to the top-most component and I believe the (outdated) docs also said something along those lines. So, that's why I wrote it that way. However, you are correct in that the root could take something other than `Unit`. I'll update the flowchart to account for that, too.
Also, AFAIK there is one distinction between a Root and other non-root components: a Root (a top-most Parent component or a Child component if there aren't any other components) does not emit messages. Or, perhaps stated differently, if it does emit messages, there isn't a higher component that can listen to those messages. If there are, then it's not covered yet in the documentation, so feel free to correct my misunderstanding if I'm wrong.

**Comment by safareli** [comment]
Root component can still emit messages, result of `runUI` is `HalogenIO query output m` : it's defined like this:
``` purs
-- | A record produced when the root component in a Halogen UI has been run.
-- | `query` allows external sources to query the root component and `subscribe`
-- | allows external consumers to receive messages raised by the root component.
type HalogenIO f o m =
  { query :: f ~> m
  , subscribe :: CR.Consumer o m Unit -> m Unit
  }
```
So you can use `query` part of it to send messages to the root component and `subscribe` part of it to subscribe to messages the root component will be emitting.

**Comment by JordanMartinez** [comment]
Ok, thanks for the correction.

**Comment by JordanMartinez** [comment]
How's this? It includes @safareli's comments, querying of children, destruction and recreation of children when a parent renders and passes in a new slot/input value, and includes the initializer and finalizer stuff. I decided not to use groups in this one since it gets tedious when modifying the flowchart. Perhaps at the final draft it would be worthwhile. 

The only thing I'm a bit uncertain about: does the root ever get destroyed and emit a Finalized message? If so, how would that happen?

![halogen - with lifecycle](https://user-images.githubusercontent.com/8413037/41871705-83f0e204-7874-11e8-83e9-8b18665d638d.png)

**Comment by safareli** [comment]
You **might** need to send some `query`  using HalogenIO, unless halogen is invoking finalizer when the node component is embedded into is removed from the DOM.

**Comment by garyb** [comment]
You could well be right - the main disadvantage is the reader can't see anything they're trying until the penultimate step there. 

I'd be tempted to say we could do it both ways and offer the choice to the user. I know personally, as someone who is somewhat familiar with a bunch of UI libraries, I want to see the big picture first since that's where the bigger differences are (compared to things like rendering HTML and such). But if someone is coming to a library like this for the first time, having the things introduced bottom-up probably would work better.

**Comment by thomashoneyman** [comment]
What do you think of putting together a documentation site like this:

https://citizennet.github.io/purescript-halogen-select/

wherein there are sections meant for that sort of difference? For example, the first section can be an overview / high-level introduction to the library, and then a dedicated walkthrough / tutorial section, and then a "concepts" section dealing with common patterns (like `ReaderT Aff`)

**Comment by thomashoneyman** [comment]
I'm sure my team at @citizennet would be willing to dedicate some time to creating a documentation website organized like that, with the guide as the single current member, but with the ability to add more. The only change for Halogen maintenance is that CI ought to rebuild the docs on a push to master. The docs can be stored in simple markdown:

https://github.com/citizennet/purescript-halogen-select/tree/master/docs

If you're open to it, we could work on a PR.

**Comment by JordanMartinez** [comment]
> Sounds like a lot of work :sweat_smile:

...which is why you let me do a large part of it :wink: as a way to learn more about Halogen and how it works.

**Comment by JordanMartinez** [comment]
(I'm posting this in other doc-related issues. Sorry for the multiple notifications.)

Just FYI. I've put together a bottom-up tutorial on Halogen for the `v5.0.0-rc.4` release: https://github.com/jordanmartinez/learn-halogen There are still a few things it doesn't cover yet, but it should get most people up to speed.

It also includes an updated version of the above flowchart.
