### ISSUE TITLE
Record creation vs record update syntax

### ISSUE THREAD

**Issue by milesfrain** [purescript-halogen/purescript-halogen#679]
A potential point of confusion for beginners might be why puns can only be used for record creation, but not record updates:

```purs
H.mkComponent
  { initialState
  , render: render                     -- optional `: render` with record creation pun
  , eval: H.mkEval $ H.defaultEval
      { handleAction = handleAction    -- mandatory ` = handleAction` with record update syntax
      , initialize = Just Initialize
      }
  }
```

Not sure if it would be helpful to make a note about this in the docs, or if sticking with the examples is good enough.

There was some discussion on modifying syntax to avoid this duplication with record updates, but it looks like that ship has sailed. https://github.com/purescript/purescript/issues/1791

**Comment by thomashoneyman** [comment]
I am open to adding a short note to the guide the first time this syntax is used, though I would rather defer any detailed explanation to another resource. That’s just because this is a guide on Halogen, not on PureScript.

I’d be happy to accept a PR which adds a short note and links to a relevant section of documentation on records for more details
