### ISSUE TITLE
Weird duplicate visual bug

### ISSUE THREAD

**Issue by JordanMartinez** [purescript-halogen/purescript-halogen#711]
I came across this bug while working on a personal project. I've provided an interactive summary showing its weirdness via Try PureScript: https://try.purescript.org/?gist=4001b31b0e3fe7ab6067c8cf1de97239

Here's the general control flow:

1. Parent component renders a box in which user can type input, and a list of items
1. User types something into the input box and presses enter
1. Component raises a message of `String` to parent
1. Parent handles message by updating its state (`Array String`) to add that element to the front of its list via `Array.cons`
1. Parent rerenders
1. Rendered list of items duplicates items in a cyclical fashion

**Comment by garyb** [comment]
This is happening because you're duplicating slot IDs. Each component needs to have a unique slot ID, but when you do, say:

``` purescript
(state <#> \itemText ->
            HH.slot _itemList 1 itemCompNoStateUsed itemText (const Nothing)
          )
```

Every `itemText` being rendered per item in the state array is being given the slot ID 1.

**Comment by garyb** [comment]
There's also an issue occurring because `itemHalogenComp` doesn't use a receiver to update the state coming from the input each time. Same problem in `itemCompStateUsed` I assume.

**Comment by garyb** [comment]
Also, just for future reference, those text blocks could probably have been entered more easily by using triple quotes rather than the `\` line continuation :smile:

**Comment by garyb** [comment]
One thing I'm not sure about is why it's not printing warnings in the console. Halogen does actually attempt to detect duplicate slot IDs and warn about it: https://github.com/purescript-halogen/purescript-halogen/blob/f491397e51858884882665783a09a5281806d729/src/Halogen/Aff/Driver.purs#L247-L248

I added that warning because duplicate slot ID can be easy to miss, and the result is generally bizarre and illogical seeming behaviour. That was what tipped me off here actually. The problem with the receivers in those other components just compounded the strangeness though, which made it take a few more minutes to diagnose.

**Comment by JordanMartinez** [comment]
Thanks Gary!

Originally, I was using 
```
flip mapWithIndex state \idx text ->
  HH.slot _item idx itemComp text (const Nothing)
```
I had forgotten about the need to add a handler to receive new inputs. As you can tell, I haven't been in Halogen land in quite a while. 

> Also, just for future reference, those text blocks could probably have been entered more easily by using triple quotes rather than the \ line continuation smile

I'm not in the habit of using triple quotes. I think the one time I did use it, it didn't work as I expected it to. So, I'm not sure whether I just used it wrong or needed to call some function afterwards.
