### ISSUE TITLE
`memoized` doesn't seem to work

### ISSUE THREAD

**Issue by garyb** [purescript-halogen/purescript-halogen#742]
`lazy`* is fine, but neither me or Nate could get `memoized` to work right.

**Comment by natefaubion** [comment]
It's because `memoized` is eta expanded, and so partial application (which is necessary) doesn't do any good.
https://github.com/purescript-halogen/purescript-halogen/blob/2f8531168207cda5256dc64da60f791afe3855dc/src/Halogen/HTML.purs#L118

Compare with Spork's implementation (which works):
https://github.com/natefaubion/purescript-spork/blob/131f07d669f2c09175faed39c3445c6a46ca924f/src/Spork/Html/Core.purs#L194
