### ISSUE TITLE
Example at docs/guide/README.md does not compile on try.purescript.org

### ISSUE THREAD

**Issue by JivanRoquet** [purescript-halogen/purescript-halogen#752]
The introductory example (the one with the increment/decrement counter) at the following page: https://github.com/purescript-halogen/purescript-halogen/blob/master/docs/guide/README.md does not compile on https://try.purescript.org.

Instead I get this error message at compilation:

```
Error 1 of 1

  Could not match type

    Action

  with type

    Maybe t0


while checking that type Action
  is at least as general as type Maybe t0
while checking that expression Decrement
  has type Maybe t0
in value declaration component

where t0 is an unknown type
```

The code is as follows:

```purescript
module Main where

import Prelude

import Effect (Effect)
import Halogen as H
import Halogen.Aff as HA
import Halogen.HTML as HH
import Halogen.HTML.Events as HE
import Halogen.VDom.Driver (runUI)

main :: Effect Unit
main = HA.runHalogenAff do
  body <- HA.awaitBody
  runUI component unit body

data Action = Increment | Decrement

component =
  H.mkComponent
    { initialState
    , render
    , eval: H.mkEval $ H.defaultEval { handleAction = handleAction }
    }
  where
  initialState _ = 0

  render state =
    HH.div_
      [ HH.button [ HE.onClick \_ -> Decrement ] [ HH.text "-" ]
      , HH.div_ [ HH.text $ show state ]
      , HH.button [ HE.onClick \_ -> Increment ] [ HH.text "+" ]
      ]

  handleAction = case _ of
    Increment -> H.modify_ \state -> state + 1
    Decrement -> H.modify_ \state -> state - 1
```

Am I missing something?

**Comment by JivanRoquet** [comment]
The issue was that the code above is from `master` so v6. The v5.1 version works on try.purescript.org.

I guess this issue might be left open because I am probably not the only one stumbling on this?

As an aside, do we have any idea on when try.purescript.org might be update to Halogen v6 and/or if there is a way to specify which version we want?

**Comment by thomashoneyman** [comment]
You’re right, this is happening because Try PureScript is still on PureScript 0.13.8 and Halogen 5; it should update to PureScript 0.14.1 and Halogen 6 sometime in the next couple of weeks. Try PureScript itself is being migrated to Halogen, in fact!

After that we do have plans to at least indicate the versions of packages and the compiler used on Try PureScript, but because the server runs the compiler with external for all packages loaded into memory it would be cost prohibitive (for now) to allow switching among multiple versions of packages or the compiler. So for that reason there aren’t current plans to allow that (it would take a proposal and serious rework of the architecture).

**Comment by JivanRoquet** [comment]
Got it. Thanks for the information.

**Comment by senorsmile** [comment]
I just ran into this same thing.  

Would we be able to add something to the guide and/or Try Purescript indicating versions? 
This would easily tell a new reader what the likely issue is.

**Comment by thomashoneyman** [comment]
Try PureScript will indicate versions in the future, but for now everything is up-to-date for PureScript 0.14. Going to close this with that in mind -- thanks for the report!
