### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by Sinha-Ujjawal** [purescript-halogen/purescript-halogen#758]
Getting error: ReferenceError: window is not defined after spago run

**Comment by thomashoneyman** [comment]
Sorry for the formatting below — I’m on mobile at the moment.

The issue is that Halogen is only usable in a browser environment (where the window object is available as part of the web APIs), but spago run will execute your code in a Node.js environment. You should instead bundle your app with spago and link to the resulting script from an HTML file. You can see examples of this in the examples directory in this project, or you can use the purescript-halogen-template repository as an easy way to get started.

**Comment by julianespinel** [comment]
Use `spago bundle-app` instead of `spago run`
