### ISSUE TITLE
No newbie path to discover how to access event input (?)

### ISSUE THREAD

**Issue by ptvirgo** [purescript-halogen/purescript-halogen#762]
How am I supposed to find out how to access the contents of an event?

Coming in brand new to PureScript this weekend.  The guide is a nice start and the api docs seem well formed, but they don't seem to provide a path to discover how to read the input from an event.

**Comment by paul-rouse** [comment]
Do you mean things like getting the text when the value of a text input field changes, or the mouse position when a mouse event occurs?  I think what you are looking for is covered in the guide, but you may have missed the significance because a parameter is ignored in the initial explanation: section 2 talks about ["Handling Events"](https://github.com/purescript-halogen/purescript-halogen/blob/master/docs/guide/02-Introducing-Components.md#handling-events), and you will see that the function passed to `onClick` actually takes a `MouseEvent` parameter, but it is ignored in that example.

If you do want to look at the data, the basic pattern is shown for an `onValueInput` handler in [section 3 of the guide](https://github.com/purescript-halogen/purescript-halogen/blob/master/docs/guide/03-Performing-Effects.md#an-aff-example-http-requests).  In that particular case, the function simply takes a `String` parameter - for other cases, like the `onClick` one, you need to look up the details in the [module documentation for Halogen.HTML.Events](https://pursuit.purescript.org/packages/purescript-halogen/6.1.2/docs/Halogen.HTML.Events) on pursuit.  If you follow the documentation through for `onClick`, say, you will find that you can get information out of a `MouseEvent`(the type passed to the `onClick` handler function) using a variety of functions, such as `screenX`, `button`, and lots more.

**Comment by ptvirgo** [comment]
Looks like you have spotted the on-boarding challenge here.

The "Handling Events" only shows an example of how to throw away your input, and the one example of keeping your input is in a later section, tucked into some source code labeled "An Aff Example: HTTP Requests."

The module documentation does have the information, and you could find it if you click through the links for onClick, and realize that you need to read the adjacent function calls.  It looks a bit different if you try to take the same path through "HTML.Events.onInput," however.

Your answers really helped me, personally.  Thanks! I can tell you've handled this kind of situation before.

If you wanted to make the documentation handle it for you, it does look like you know where the challenges for new folks are.

**Comment by thomashoneyman** [comment]
Great answer, @paul-rouse! It either of y’all have an idea of where in the guide it would make the most sense to add a (short) section about this, I do think it would make a good addition.

**Comment by ptvirgo** [comment]
Yes - in case it was any way unclear, that really helped me out.  Thank you @paul-rouse.

I'm not sure of the exact wording, but a quick addition to the handling events section might say: "When you're ready to start using other events, the Halogen.HTML.Events library (link to pursuit) gives you access to HTML events, and purescript-web-uievents (link to pursuit) gives you tools to access event data."

You could always go for more, but those two details were enough to get me from "stuck" to "unstuck."  Thanks for that.

**Comment by paul-rouse** [comment]
I'll put some ideas into a PR tomorrow.
