### ISSUE TITLE
Question About Updating EventSource from Halogen v5 to v6

### ISSUE THREAD

**Issue by blinky3713** [purescript-halogen/purescript-halogen#773]
Previously in v5 I used a common pattern to spawn an `Aff` thread to read from a global message bus and pass off relevant messages as actions to the component's handlers. For example:

```purescript
  handleAction = case _ of
    Initialize -> do
      { messageBus } <- ask
      _ <-
        H.subscribe
          $ HES.affEventSource \emitter -> do
              fiber <-
                H.liftEffect $ launchAff
                  $ fix \loop -> do
                      msg <- Bus.read messageBus
                      case msg of
                        ...
                      loop
              pure $ HES.Finalizer $ killFiber (error "cleanup") fiber
      pure unit
    ...
```

With new way of doing things via coroutines, I don't see any equivalent of `HES.Finalizer`. Instead I end up having to store the fiber in the state myself and then hook in to the `Finalize` action to grab the fiber and cancel it manually.

As far as I can tell, this is not covered in the upgrade guide explicitly, but maybe I overlooked something. Whether it's reading from a message bus or some other loop, probably other people have a similar problem. What is the "correct" way of dealing with this in Halogen 6, and could we explicitly put it in the guide?

**Comment by garyb** [comment]
I think you may be misreading something, as the event sources in v6 are no longer coroutines, but they were previously. Although I suppose that's irrelevant to the actual question here!

You can have custom unsubscription behaviour with `halogen-subscription` using `makeEmitter`, so you'd have something like:

``` purescript
H.subscribe $ HES.makeEmitter \emit ->
  -- ... do whatever with the `emit` callback ...
  pure (pure unit) -- this inner `pure unit` is the action that will run on unsubscription
```

But for the case you're dealing with here, you can probably do away with the `Aff` bus and instead use `halogen-subscription` directly - create a `SubscriptionIO` at the top level and put that in your `MonadReader` environment, rather than the bus, and then you can subscribe directly to the `emitter` and write to the `listener` in the `SubscriptionIO` instead.

**Comment by blinky3713** [comment]
> I think you may be misreading something, as the event sources in v6 are no longer coroutines, but they were previously. Although I suppose that's irrelevant to the actual question here!

doh! 🤦 yes this is what I meant

ok let me see if I can give that a shot. On the separate issue, do you think it's worth putting in the guide ?

**Comment by garyb** [comment]
Yeah, probably! I was supposed to write the "concepts reference" part of the docs that would have more details about this sort of thing in it, but... uh 👀, so maybe something about it in the guide in the mean time would be better.

**Comment by blinky3713** [comment]
actually, follow up question about the `makeEmitter` route, wouldn't I end up with the same problem? I would do something like:

```purescript
H.subscribe $ HES.makeEmitter \emit -> do
  fiber <- launchAff 
    $ fix \loop -> do
          msg <- Bus.read messageBus
          case msg of
              ...
          loop
  pure $ killFiber (error "cleanup") fiber
```

but now I'm just ignoring the return value of type `Subscription`. If I don't manually call `unsubscribe` on this via the `Finalize` action in the same way that I described in the original question, don't I end up with the same problem of some zombie `Aff` thread?

**Comment by garyb** [comment]
Subscriptions and forks are automatically cleaned up when a component finalizes, regardless of whether you do it manually in `Finalize`. It's actually pretty rare that finalizers need using now, because of that. You should be able to verify what I'm saying by putting a `traceM` or `log` in the subscription canceller/cleanup thing, and see that it fires when you unmount the component even if you ignore the `H.subscribe` result. 🙂

**Comment by blinky3713** [comment]
Awesome! Happy to close this issue, but one final question. Feel free to say as little as you want, but I find it curious enough: 

> Subscriptions and forks are automatically cleaned up when a component finalizes, regardless of whether you do it manually in Finalize.

Regarding forks, was this already the case in `v5` and I was just wasting energy doing this all myself?

**Comment by garyb** [comment]
I'm pretty sure we had that in place by v5 yeah :smile:

**Comment by garyb** [comment]
Looks like it was introduced in v1.0.0 actually!

**Comment by blinky3713** [comment]
Yeah I guess it's above my understanding, just looking at the codebase now I can see that if you use this version of fork

https://github.com/purescript-halogen/purescript-halogen/blob/79cdc347093d664ce57d10ada5c33f177acdfbc4/src/Halogen/Query/HalogenM.purs#L215

that you would register the fiber with the `Driver` but I would think that I could still launch zombie `Aff` forks all day. I do see how if I use this version of `subscribe`

https://github.com/purescript-halogen/purescript-halogen/blob/79cdc347093d664ce57d10ada5c33f177acdfbc4/src/Halogen/Query/HalogenM.purs#L172

that I get what you're talking about though, so happy with that

**Comment by garyb** [comment]
The "magic" happens in the driver part of Halogen, if you check out the way `Fork` and `Subscribe` are handled [in here](https://github.com/purescript-halogen/purescript-halogen/blob/79cdc347093d664ce57d10ada5c33f177acdfbc4/src/Halogen/Aff/Driver/Eval.purs#L83) you can see that it writes an entry into the `forks` or `subscription` `Ref` that is part of the component's internal state, so that later we can traverse these and clean them up.
