### ISSUE TITLE
Naming : short type variables

### ISSUE THREAD

**Issue by ocramz** [purescript-halogen/purescript-halogen#783]
I find it a bit unfortunate that authors settled on long type variable names, which in some cases (e.g. `query`) coincide with those of related functions, e.g. in `HalogenIO` https://pursuit.purescript.org/packages/purescript-halogen/6.1.2/docs/Halogen#t:HalogenIO 

```purescript
type HalogenIO query output m = { dispose :: m Unit, messages :: Emitter output, query :: forall a. query a -> m (Maybe a) }
```

This complicates searching for a term within a page (which is still faster than Pursuit's search bar)

**Comment by garyb** [comment]
We started using these names because people had a hard time in the past when they were abbreviated, so it seems we can't really win here. I've not heard this complaint before and nobody has talked about the type parameters since we renamed them, so I think keeping things as they are is the way to go for now, unless more people raise this issue.
