### ISSUE TITLE
Attribute "value" for tag "meter" is broken

### ISSUE THREAD

**Issue by flip111** [purescript-halogen/purescript-halogen#785]
https://github.com/purescript-halogen/purescript-halogen/blob/v6.1.3/src/Halogen/HTML/Properties.purs#L238

https://github.com/purescript-halogen/purescript-dom-indexed/blob/v8.0.0/src/DOM/HTML/Indexed.purs#L446

**Comment by garyb** [comment]
The fix for this is to relax the type of the `value` prop definition so it accepts an `IsProp` constrained value, rather than a monomorphic `String`. See the `type_` above `value` in the source for an existing example of this.

We should probably do an audit of all the property types and ensure that any that are shared across elements but have different possible values are changed to follow the same scheme.

This is a potentially breaking change unfortunately, as adding the constraint could mess with type inference if someone is putting a `value` prop into a record, due to the less than ideal behaviours that arise there sometimes. It's unlikely anyone is doing that, but it's still a possibility.
